services:
  - docker

env:
  - TEST_GROUP=2-4-1
  - TEST_GROUP=2-4-2
  - TEST_GROUP=2-4-3
  - TEST_GROUP=2-4-4
  - TEST_GROUP=2-4-5
  - TEST_GROUP=2-latest

before_install:
  - travis_retry wget https://github.com/docker/compose/releases/download/v2.17.0/docker-compose-linux-x86_64
  - sudo mv docker-compose-linux-x86_64 /usr/libexec/docker/cli-plugins/docker-compose
  - sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose
  - docker --version && docker compose version
  - composer self-update --2 && composer self-update --2.2

install:
  - composer install --no-interaction
script:
    - composer run test-static-analysis
    - composer run test:unit
    # Install magento
    - CURRENT_EXTENSION="." COMPOSER_MODULE_SYMLINK=0 UNIT_TESTS_PATH='dev/Test/Unit' INTEGRATION_TESTS_PATH='dev/Test/Integration' vendor/bin/mtest-make $TEST_GROUP
    # Ensure magento composer installer is creating the di.xml file as necessary
    - vendor/bin/mtest 'test -f app/etc/di.xml_ampersand_magento2_verbose_log_request/di.xml'
    # Integration tests
    - vendor/bin/mtest "vendor/bin/phpunit -c /var/www/html/dev/tests/integration/phpunit.xml.dist --testsuite Integration --debug"

after_failure:
  - vendor/bin/mtest 'cat /var/www/html/var/log/*.log'
  - vendor/bin/mtest 'for r in ./var/report/*; do cat $r; done'
  - vendor/bin/mtest 'ls -l ./dev/tests/integration/tmp/sandbox*/var'
  - vendor/bin/mtest 'for r in ./dev/tests/integration/tmp/sandbox*/var/report/*; do cat $r; done'
  - vendor/bin/mtest 'for l in ./dev/tests/integration/tmp/sandbox*/var/log/*; do cat $l; done'
  - sleep 10;
